```{r}
# Load the necessary libraries
library(plotly)
library(dplyr)
library(readr)

# Load your dataset
data <- read_csv("./data/stroke_prediction_dataset.csv")

# Convert Diagnosis to a binary outcome (0 = No Stroke, 1 = Stroke)
data$Diagnosis <- ifelse(data$Diagnosis == "Stroke", 1, 0)

# Create a summary data frame for count of diagnoses and total observations grouped by Dietary Habits and Alcohol Intake
summary_data <- data %>%
  group_by(`Dietary Habits`, `Alcohol Intake`) %>%
  summarize(Total_Obs = n(),
            Stroke_Count = sum(Diagnosis), 
            Stroke_Rate = sum(Diagnosis) / n() * 100, 
            .groups = 'drop')

# Create an interactive bubble plot using plotly, using stroke rate as the size of the bubbles
plot <- plot_ly(summary_data, x = ~`Dietary Habits`, y = ~`Alcohol Intake`, size = ~Stroke_Rate,
                text = ~paste("Stroke Count:", Stroke_Count,
                              "<br>Total Observations:", Total_Obs,
                              "<br>Stroke Rate:", sprintf("%.2f%%", Stroke_Rate),
                              "<br>Dietary Habits:", `Dietary Habits`, 
                              "<br>Alcohol Intake:", `Alcohol Intake`),
                type = 'scatter', mode = 'markers',
                marker = list(color = 'orange', opacity = 0.6, sizemode = 'diameter')) %>%
  layout(title = "Interactive Bubble Plot of Stroke Rate by Dietary Habits and Alcohol Intake",
         xaxis = list(title = "Dietary Habits"),
         yaxis = list(title = "Alcohol Intake"),
         showlegend = FALSE)

# Display the plot
plot
```


```{r}
library(wordcloud)
library(tm)
library(RColorBrewer)
```

```{r}
stroke_data <- data %>%
  filter(Diagnosis == 1)
symptoms_text <- stroke_data$Symptoms
symptoms_text <- na.omit(symptoms_text)
corpus <- Corpus(VectorSource(symptoms_text))
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
custom_stopwords <- c("symptom", "symptoms")
corpus <- tm_map(corpus, removeWords, custom_stopwords)

tdm <- TermDocumentMatrix(corpus)
m <- as.matrix(tdm)
word_freqs <- sort(rowSums(m), decreasing = TRUE)
word_freqs <- data.frame(word = names(word_freqs), freq = word_freqs)
num_words <- min(100, nrow(word_freqs))

wordcloud(words = word_freqs$word, freq = word_freqs$freq, scale = c(3, 0.5), 
          max.words = num_words, random.order = FALSE, rot.per = 0.35, 
          colors = colorRampPalette(brewer.pal(9, "Blues"))(num_words))
```

